### ISSUE TITLE
Do we expect LTS for this plugin?

### ISSUE THREAD

**Issue by reified** [jvilya/sonar-android-plugin#3]
Hi @jvilya I am really impressed with this plugin.  thanks for your love and contribution.

before we wanted to use this plugin in production, we have couple of questions , posted below.? would be great if you can address it.

1.  When can we expect this plugin to be published in sonar marketplace officially.
2.  What about Long term support?

**Comment by jvilya** [comment]
Hello @vb-hp!

You are welcome.

> What about Long term support?  

I want to notice that it's the open-source project that I'm doing in my free time. I'm not a company and couldn't provide any guarantees for LTS. But the project's license allows you to make the fork and continue support at any time.

> When can we expect this plugin to be published in sonar marketplace officially.  

It's on my TODO list. I'll make an issue for making it more visible.

**Comment by jvilya** [comment]
Here is the issue for marketplace: #4

**Comment by reified** [comment]
@jvilya thanks for the update.
